# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Satisco Application Integration
email: a.danset@satisco.com
description: Documentation about SAI
baseurl: ""
url: ""

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/img/branding/SATISCO-logo-full.png"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Satisco. All rights reserved. Designed and build by Anthony DANSET"


# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
remote_theme: just-the-docs/just-the-docs
color_scheme: satisco
plugins:
  - jekyll-feed

# Git
github_username:  ThonyTruant
