# Site settings
title: Anthony's website V0.0.0_01
email: a.danset@satisco.com
description: > # this means to ignore newlines until "baseurl:"
  To be defined
baseurl: "/FCT--Documentation" # the subpath of your site, e.g. /blog/
url: "https://satisco-com.github.io/FCT--Documentation/" # the base hostname & protocol for your site
github_username:  ThonyTruant

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

theme: jekyll-theme-slate
