# Site settings
title: Satisco Control Tower
email: a.danset@satisco.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/FCT--Documentation" # the subpath of your site, e.g. /blog/
url: "https://satisco-com.github.io/FCT--Documentation/" # the base hostname & protocol for your site
github_username:  ThonyTruant

# Build settings
markdown: kramdown

theme: jekyll-theme-slate
